<?php
/**
 * INIT A CRT APPLICATION.
 *
 * Usage php init.php [-f] [-h]
 */

$usage = <<<USAGE
Usage: php init.php [-f] [-h]
Params:
	-f generate files only (not directories)
	-h display this message

USAGE;

$options = getopt('fh');

if(isset($options['h'])) {
	print_r($usage);
	exit(0);
}

if(isset($options['f'])) {
	$fileOnly = TRUE;
} else {
	$fileOnly = FALSE;
}

define("CRT_ROOT_DIRECTORY", realpath(dirname(__FILE__).'/..'));
define("CRT_APPLICATION_DIRECTORY", CRT_ROOT_DIRECTORY.'/application');
define("CRT_MODEL_DIRECTORY", CRT_APPLICATION_DIRECTORY.'/model');
define("CRT_VIEW_DIRECTORY", CRT_APPLICATION_DIRECTORY.'/view');
define("CRT_CONTROLLER_DIRECTORY", CRT_APPLICATION_DIRECTORY.'/controller');

// Create directories
echo "\n **** Initialize CRT application **** \n\n";

if(!$fileOnly) {
	mkdir(CRT_APPLICATION_DIRECTORY);
	echo "  ->  Create directory ".CRT_APPLICATION_DIRECTORY."\n";
	mkdir(CRT_MODEL_DIRECTORY);
	echo "  ->  Create directory ".CRT_MODEL_DIRECTORY."\n";
	mkdir(CRT_VIEW_DIRECTORY);
	echo "  ->  Create directory ".CRT_VIEW_DIRECTORY."\n";
	mkdir(CRT_CONTROLLER_DIRECTORY);
	echo "  ->  Create directory ".CRT_CONTROLLER_DIRECTORY."\n";
}

$disclaimer = '/**
 * This code has been generated by tools/init.php.
 *
 * Sincerely,
 * CRT
 */';

// Create hello world files
$file = CRT_CONTROLLER_DIRECTORY."/index.ctrl.php";
echo "  ->  Create file $file\n";
file_put_contents($file, '<?php
'.$disclaimer.'
class IndexController extends Controller {

	protected function crt() {

		/**
		 * Insert functionnal code here ...
		 */

		$this->data[\'number\'] = mt_rand(0, 10);

	}

}
');

$file = CRT_CONTROLLER_DIRECTORY."/error.ctrl.php";
echo "  ->  Create file $file\n";
file_put_contents($file, '<?php
'.$disclaimer.'
class ErrorController extends Controller {

	protected function crt() {
	}

}
');

$file = CRT_VIEW_DIRECTORY."/index.view.php";
echo "  ->  Create file $file\n";
file_put_contents($file, '<?php
'.$disclaimer.'
class IndexView extends View {

	protected function crt() {

		/*
		 * Insert View Code Here ...
		 */

		echo "Hello World ! <br/>".$this->data[\'number\'];

	}

}
');

$file = CRT_VIEW_DIRECTORY."/error.view.php";
echo "  ->  Create file $file\n";
file_put_contents($file, '<?php
'.$disclaimer.'
class ErrorView extends View {

	protected function crt() {
		echo "<h1>Error 404 !</h1>";
		echo "<p>
			This page handles 404 redirection.<br/>
			Sorry but this url can\'t be resolved by server.
		</p>";
	}

}
');

$file = CRT_MODEL_DIRECTORY."/Log.bean.php";
echo "  ->  Create file $file\n";
file_put_contents($file, '<?php
'.$disclaimer.'
class Log extends Bean {

	protected $databaseName = "default_database"; // TODO edit this value

	public function printLn() {
		echo "$this->user at $this->date <br/>";
	}

}
');

echo "\n **** Done ! **** \n\n";
